### ISSUE TITLE
Ajout d'un système de retry de backup

### ISSUE THREAD

**Issue by rygilles** [web-id-fr/boo#29]

**Comment by tech-web-id** [comment]
Projet workflow associé 30001 :
- [saisir son temps](https://contact.prestaconcept.net/temps_passe/suivi/fiche_suivi.php?id_projet=30001)
- [voir le temps passé](https://contact.prestaconcept.net/temps_passe/stats/index.php?flag=consulter&id_projet=30001&id_societe=260)
