### ISSUE TITLE
Bug sur l'option de retry des backups

### ISSUE THREAD

**Issue by rygilles** [web-id-fr/boo#31]
La config n'est pas prise en compte si la valeur attempts est supérieur à 1

**Comment by tech-web-id** [comment]
Projet workflow associé 30047 :
- [saisir son temps](https://contact.prestaconcept.net/temps_passe/suivi/fiche_suivi.php?id_projet=30047)
- [voir le temps passé](https://contact.prestaconcept.net/temps_passe/stats/index.php?flag=consulter&id_projet=30047&id_societe=260)
